# Generated by scripts/generateBotWire.mjs. Do not edit.
# SDK vendoring adaptations (see README.md in this directory): type annotations
# and casts for `mypy --strict`, ruff formatting. No behavioural edits.
from __future__ import annotations

from typing import Literal, cast
from uuid import UUID

from .constants import (
    bot_wire_decision_kinds,
    bot_wire_event_kinds,
    bot_wire_game_setup_reserved_slots,
    bot_wire_message_kinds,
    bot_wire_payment_rule_ids,
    bot_wire_protocol_versions,
    bot_wire_response_action_kinds,
)
from .types import (
    AuctionResolvedEvent,
    CommonEvent,
    DecisionRequest,
    DecisionResponse,
    Frame,
    GameSetupEvent,
    HeartbeatRequest,
    HeartbeatResponse,
    InfoRevealedEvent,
    PaymentRule,
    TurnOpenedEvent,
)

max_safe_integer = 9_007_199_254_740_991
# The largest magnitude a signed varint can carry (#629). Zigzag doubles the
# magnitude before it reaches _encode_varint, so the unsigned form's safe-integer
# ceiling halves here: 2**52 - 1. The same number as maxSafeSignedInteger in the
# TypeScript codec, so neither side can encode a value the other rejects.
max_safe_signed_integer = 4_503_599_627_370_495
# The same bound under the SDK's public name: a v3 encoder has to know the range
# it may offer a caller, and a test asserting the edge must read the bound rather
# than transcribe it. botWireMaxSafeSignedInteger in the TypeScript codec is the
# same number.
bot_wire_max_safe_signed_integer = max_safe_signed_integer

# The protocol versions this codec speaks (#630): the schema's set, not a range,
# so a v4 is rejected until its layout exists here. Mirrors
# isBotWireProtocolVersion in the TypeScript codec.
supported_protocol_versions = frozenset(bot_wire_protocol_versions.values())
_payment_rule_by_id = {wire_id: rule for rule, wire_id in bot_wire_payment_rule_ids.items()}


def is_protocol_version(value: object) -> bool:
    # `bool` is excluded for the same reason _is_wire_int excludes it: True == 1
    # in Python, and a stray flag must not read as a version.
    return (
        isinstance(value, int)
        and not isinstance(value, bool)
        and value in supported_protocol_versions
    )


def _assert_protocol_version(value: object) -> int:
    if not is_protocol_version(value):
        raise ValueError("unsupported bot wire protocol version")
    return cast(int, value)


def _carries_v3_game_setup(protocol_version: int) -> bool:
    """The ONE layout switch (#630), mirroring carriesV3GameSetup in TypeScript.

    v3 changed exactly one record, gameSetup: it gained the payment-rule
    discriminant, its six chart cells became signed varints (so a custom chart's
    negative cell round trips, #524/#629), and it ends in
    bot_wire_game_setup_reserved_slots presence slots for fields the server does
    not yet send. Every other record and frame is byte-identical between the two
    versions apart from the version varint that opens each frame.
    """
    return protocol_version == bot_wire_protocol_versions["v3"]


def _payment_rule_id(rule: object) -> int:
    # `isinstance` first: `in` on a dict raises TypeError for an unhashable
    # value, and the answer for a non-string is the same refusal as for an
    # unknown one (the TypeScript codec refuses a coercible non-string too).
    if not isinstance(rule, str) or rule not in bot_wire_payment_rule_ids:
        raise ValueError("unknown bot wire payment rule")
    return bot_wire_payment_rule_ids[rule]


def _is_seat(value: int) -> bool:
    return 0 <= value <= 4


def _is_suit_id(value: int) -> bool:
    return 1 <= value <= 5


def _is_action_id(value: int) -> bool:
    return 1 <= value <= 6


def _is_objective_id(value: int) -> bool:
    return 1 <= value <= 30


def _is_wire_int(value: object) -> bool:
    """True for a value the wire may encode as an integer (#629 review).

    `bool` is excluded EXPLICITLY, and that is the whole point: `bool` subclasses
    `int` in Python, so `isinstance(True, int)` is True and a stray flag from
    dynamically-sourced data would encode as a perfectly valid 1 or 0 rather than
    failing. The TypeScript encoders reject the same inputs through
    `Number.isSafeInteger` (a boolean is not a number there), so without this the
    two runtimes disagree about what is encodable -- and the Python side is the
    permissive one, which is the direction that corrupts a frame instead of
    rejecting it.

    Used by BOTH integer encoders. The unsigned one had no type check at all, so
    a non-int also reached the comparisons below and raised TypeError instead of
    the ValueError the callers handle; short-circuiting here fixes that too.
    """
    return isinstance(value, int) and not isinstance(value, bool)


def _encode_varint(value: int) -> bytes:
    if not _is_wire_int(value) or value < 0 or value > max_safe_integer:
        raise ValueError("bot wire integer must be an unsigned safe integer")
    output = bytearray()
    while True:
        byte = value & 0x7F
        value >>= 7
        output.append(byte | (0x80 if value else 0))
        if not value:
            return bytes(output)


def _encode_signed_varint(value: int) -> bytes:
    """Zigzag-encoded signed varint (#629).

    _encode_varint rejects a negative outright, and custom chart cells can be
    negative under the #524 envelope. Zigzag (0, -1, 1, -2, 2 -> 0, 1, 2, 3, 4)
    keeps a small magnitude short in BOTH directions. A second primitive, not a
    widening of the unsigned form: a field declared unsigned must keep failing
    closed on a negative.
    """
    if (
        not _is_wire_int(value)
        or value < -max_safe_signed_integer
        or value > max_safe_signed_integer
    ):
        raise ValueError("bot wire signed integer is out of range")
    return _encode_varint(value * 2 if value >= 0 else value * -2 - 1)


def _encode_presence(present: bool) -> bytes:
    """A field-presence flag (#629): one byte, 0 or 1, written before an optional
    field's value. This is what lets v3 carry data the server does not promise to
    send -- rating information is the named first tenant -- so a later addition
    costs no version bump. The flag is written even when the field is absent;
    that is the point, and it is why the absent path is the one that runs.
    """
    # Truthiness would accept anything (#629 review): `None` writes an absence
    # byte, `1` and the STRING "false" both write a presence byte. Python
    # annotations are not enforced at runtime, so dynamically-sourced SDK data
    # reaches here unchecked, and an optional v3 field would then carry the
    # wrong presence state rather than failing. Same rule as `_is_wire_int`
    # above: validate the wire input, do not coerce it.
    if not isinstance(present, bool):
        raise ValueError("bot wire field presence flag must be a bool")
    return bytes([1 if present else 0])


class _Reader:
    def __init__(self, data: bytes):
        self.data = data
        self.offset = 0

    def read(self, length: int) -> bytes:
        end = self.offset + length
        if end > len(self.data):
            raise ValueError("bot wire frame is truncated")
        value = self.data[self.offset : end]
        self.offset = end
        return value

    def varint(self) -> int:
        start = self.offset
        value = 0
        shift = 0
        for _ in range(8):
            byte = self.read(1)[0]
            value |= (byte & 0x7F) << shift
            if value > max_safe_integer:
                raise ValueError("bot wire integer overflow")
            if byte & 0x80 == 0:
                if self.offset - start > 1 and byte == 0:
                    raise ValueError("bot wire varint is not canonical")
                return value
            shift += 7
        raise ValueError("bot wire integer overflow")

    def signed_varint(self) -> int:
        """Inverse of _encode_signed_varint. See its note for why zigzag."""
        zigzag = self.varint()
        value = zigzag >> 1 if zigzag % 2 == 0 else -((zigzag + 1) >> 1)
        # varint() accepts the full unsigned safe-integer range, which is twice
        # what the encoder can produce -- so the top half of it decodes to a
        # magnitude no encoder on either side could have written. Reject it
        # rather than hand back a value the round trip does not hold for.
        if value < -max_safe_signed_integer or value > max_safe_signed_integer:
            raise ValueError("bot wire signed integer is out of range")
        return value

    def presence(self) -> bool:
        """Inverse of _encode_presence.

        Anything but 0 or 1 is rejected rather than coerced: a stray byte here
        would silently shift every field after it.
        """
        byte = self.read(1)[0]
        if byte not in (0, 1):
            raise ValueError("bot wire field presence flag must be 0 or 1")
        return byte == 1

    def finish(self) -> None:
        if self.offset != len(self.data):
            raise ValueError("bot wire frame has trailing bytes")


def encode_signed_varint(value: int) -> bytes:
    """Single-value form of the #629 signed-varint primitive.

    The v3 gameSetup record is what uses _encode_signed_varint /
    _Reader.signed_varint directly.
    """
    return _encode_signed_varint(value)


def decode_signed_varint(data: bytes) -> int:
    reader = _Reader(data)
    value = reader.signed_varint()
    reader.finish()
    return value


def encode_presence(present: bool) -> bytes:
    """Single-value form of the #629 field-presence primitive."""
    return _encode_presence(present)


def decode_presence(data: bytes) -> bool:
    reader = _Reader(data)
    value = reader.presence()
    reader.finish()
    return value


def _encode_event(event: CommonEvent, protocol_version: int) -> bytes:
    output = bytearray()
    output += _encode_varint(bot_wire_event_kinds[event.kind])
    if isinstance(event, GameSetupEvent):
        output += _encode_varint(event.player_count)
        output += _encode_varint(event.starting_cash)
        # Validated under BOTH layouts, even though only v3 writes it: an unknown
        # rule is a caller bug whichever version is live.
        rule_id = _payment_rule_id(event.payment_rule)
        if _carries_v3_game_setup(protocol_version):
            output += _encode_varint(rule_id)
            for value in event.value_chart:
                output += _encode_signed_varint(value)
        else:
            # v2 has no field for the payment rule and cannot grow one without
            # becoming v3, so it is dropped rather than refused. Unobservable by
            # construction: a v2 bot is never seated in a second-price room
            # (getWireBotRulesetRefusal, apps/server) -- the same gate that keeps
            # it out of a custom-chart room whose negative cell the unsigned
            # encoder below would refuse.
            for value in event.value_chart:
                output += _encode_varint(value)
        output += _encode_varint(event.initial_tiebreak_seat + 1)
        output += _encode_varint(len(event.objective_ids))
        for value in event.objective_ids:
            output += _encode_varint(value)
        if _carries_v3_game_setup(protocol_version):
            # Every reserved slot is written ABSENT today; see _decode_event for
            # what a present one looks like and why a reader can skip it.
            for _ in range(bot_wire_game_setup_reserved_slots):
                output += _encode_presence(False)
    elif isinstance(event, TurnOpenedEvent):
        output += _encode_varint(event.action_id)
        output += _encode_varint(event.resource_ids[0])
        output += _encode_varint(event.resource_ids[1])
    elif isinstance(event, AuctionResolvedEvent):
        output += _encode_varint(len(event.bids_by_seat))
        for value in event.bids_by_seat:
            output += _encode_varint(value)
    elif isinstance(event, InfoRevealedEvent):
        output += _encode_varint(event.suit_id)
    return bytes(output)


def encode_frame(frame: Frame, *, protocol_version: int) -> bytes:
    """Encodes `frame` in the given protocol version (#630).

    Keyword-only and required on purpose: an SDK states the version it
    negotiated at the handshake rather than inheriting a module default that a
    server-side flag flip would silently make wrong.
    """
    _assert_protocol_version(protocol_version)
    output = bytearray()
    output += _encode_varint(protocol_version)
    output += _encode_varint(bot_wire_message_kinds[frame.kind])
    output += UUID(frame.request_id).bytes
    if isinstance(frame, HeartbeatRequest):
        output += _encode_varint(frame.deadline_at)
    elif isinstance(frame, DecisionRequest):
        output += _encode_varint(frame.deadline_at)
        output += _encode_varint(bot_wire_decision_kinds[frame.decision_kind])
        common = bytearray()
        common += _encode_varint(len(frame.common_events))
        for event in frame.common_events:
            common += _encode_event(event, protocol_version)
        output += _encode_varint(len(common))
        output += common
        output += _encode_varint(frame.bot_seat + 1)
        output += _encode_varint(len(frame.current_hand_suit_ids))
        for suit_id in frame.current_hand_suit_ids:
            output += _encode_varint(suit_id)
    elif isinstance(frame, DecisionResponse):
        output += _encode_varint(bot_wire_response_action_kinds[frame.action_kind])
        if frame.action_kind == "pass":
            if frame.value is not None:
                raise ValueError("pass responses must not include a value")
        else:
            if frame.value is None:
                raise ValueError("decision responses must include a value")
            output += _encode_varint(frame.value)
    return bytes(output)


def _decode_event(reader: _Reader, protocol_version: int) -> CommonEvent:
    kind = reader.varint()
    if kind == bot_wire_event_kinds["gameSetup"]:
        player_count = reader.varint()
        if player_count < 3 or player_count > 5:
            raise ValueError("invalid player count")
        starting_cash = reader.varint()
        v3 = _carries_v3_game_setup(protocol_version)
        payment_rule: PaymentRule = "first-price"
        if v3:
            decoded_rule = _payment_rule_by_id.get(reader.varint())
            if decoded_rule is None:
                raise ValueError("unknown bot wire payment rule")
            payment_rule = cast(PaymentRule, decoded_rule)
        value_chart = cast(
            tuple[int, int, int, int, int, int],
            tuple((reader.signed_varint() if v3 else reader.varint()) for _ in range(6)),
        )
        seat = reader.varint() - 1
        if not _is_seat(seat) or seat >= player_count:
            raise ValueError("invalid tiebreak seat")
        objective_count = reader.varint()
        if objective_count > 30:
            raise ValueError("invalid objective count")
        objective_ids = tuple(reader.varint() for _ in range(objective_count))
        if not all(_is_objective_id(objective_id) for objective_id in objective_ids):
            raise ValueError("invalid objective id")
        if v3:
            for _ in range(bot_wire_game_setup_reserved_slots):
                # A reserved slot is a presence flag and, when present, a
                # LENGTH-PREFIXED payload whose inner layout the schema defines
                # once a tenant claims the slot. Length-prefixed so a reader that
                # predates the tenant skips it here instead of being stranded:
                # the point of reserving the slot is that the addition costs no
                # version bump (#629), and that only holds if an older reader is
                # not broken by the newer writer.
                if reader.presence():
                    reader.read(reader.varint())
        return GameSetupEvent(
            "gameSetup", player_count, starting_cash, value_chart, seat, objective_ids, payment_rule
        )
    if kind == bot_wire_event_kinds["turnOpened"]:
        action_id = reader.varint()
        first_resource = reader.varint()
        second_resource = reader.varint()
        if not _is_action_id(action_id):
            raise ValueError("invalid action id")
        if (first_resource != 0 and not _is_suit_id(first_resource)) or (
            second_resource != 0 and not _is_suit_id(second_resource)
        ):
            raise ValueError("invalid resource id")
        return TurnOpenedEvent("turnOpened", action_id, (first_resource, second_resource))
    if kind == bot_wire_event_kinds["auctionResolved"]:
        bid_count = reader.varint()
        if bid_count < 3 or bid_count > 5:
            raise ValueError("invalid bid count")
        return AuctionResolvedEvent(
            "auctionResolved", tuple(reader.varint() for _ in range(bid_count))
        )
    if kind == bot_wire_event_kinds["infoRevealed"]:
        suit_id = reader.varint()
        if not _is_suit_id(suit_id):
            raise ValueError("invalid suit id")
        return InfoRevealedEvent("infoRevealed", suit_id)
    raise ValueError("unknown bot wire event kind")


def _decode_events(reader: _Reader, protocol_version: int) -> tuple[CommonEvent, ...]:
    event_count = reader.varint()
    if event_count > 128:
        raise ValueError("invalid event count")
    events = tuple(_decode_event(reader, protocol_version) for _ in range(event_count))
    if not events or events[0].kind != "gameSetup":
        raise ValueError("game setup must be first")
    if any(event.kind == "gameSetup" for event in events[1:]):
        raise ValueError("duplicate game setup")
    has_open_turn = False
    for event in events[1:]:
        if event.kind == "turnOpened":
            if has_open_turn:
                raise ValueError("invalid bot wire event order")
            has_open_turn = True
        elif event.kind == "auctionResolved":
            if not has_open_turn:
                raise ValueError("invalid bot wire event order")
            has_open_turn = False
        elif event.kind == "infoRevealed" and has_open_turn:
            raise ValueError("invalid bot wire event order")
    return events


def decode_frame(data: bytes, *, protocol_version: int | None = None) -> Frame:
    """Decodes a frame in whichever supported version its header names (#630).

    With `protocol_version` given, a frame in any OTHER version is rejected --
    the server's posture, since it serves exactly one version at a time and a
    response in the other one is as malformed as a bad byte. An SDK that
    negotiated its version at the handshake may omit it: the server only ever
    sends the negotiated one.
    """
    # An unsupported expectation is refused as such, not reported as a
    # mismatch against every frame.
    if protocol_version is not None:
        _assert_protocol_version(protocol_version)
    reader = _Reader(data)
    frame_version = _assert_protocol_version(reader.varint())
    if protocol_version is not None and frame_version != protocol_version:
        raise ValueError("unexpected bot wire protocol version")
    kind = reader.varint()
    request_id = str(UUID(bytes=reader.read(16)))
    frame: Frame
    if kind == bot_wire_message_kinds["heartbeatRequest"]:
        frame = HeartbeatRequest("heartbeatRequest", request_id, reader.varint())
    elif kind == bot_wire_message_kinds["heartbeatResponse"]:
        frame = HeartbeatResponse("heartbeatResponse", request_id)
    elif kind == bot_wire_message_kinds["decisionRequest"]:
        deadline_at = reader.varint()
        decision_value = reader.varint()
        common_reader = _Reader(reader.read(reader.varint()))
        events = _decode_events(common_reader, frame_version)
        common_reader.finish()
        decision_kind: Literal["submitBid", "selectInfoToReveal"]
        if decision_value == bot_wire_decision_kinds["submitBid"]:
            decision_kind = "submitBid"
        elif decision_value == bot_wire_decision_kinds["selectInfoToReveal"]:
            decision_kind = "selectInfoToReveal"
        else:
            raise ValueError("unknown decision kind")
        seat = reader.varint() - 1
        if not _is_seat(seat):
            raise ValueError("invalid bot seat")
        hand_count = reader.varint()
        if hand_count > 10:
            raise ValueError("invalid private hand count")
        hand = tuple(reader.varint() for _ in range(hand_count))
        if not all(_is_suit_id(suit_id) for suit_id in hand):
            raise ValueError("invalid private hand suit")
        frame = DecisionRequest(
            "decisionRequest", request_id, deadline_at, decision_kind, events, seat, hand
        )
    elif kind == bot_wire_message_kinds["decisionResponse"]:
        action_value = reader.varint()
        if action_value == bot_wire_response_action_kinds["pass"]:
            frame = DecisionResponse("decisionResponse", request_id, "pass")
        elif action_value == bot_wire_response_action_kinds["submitBid"]:
            frame = DecisionResponse("decisionResponse", request_id, "submitBid", reader.varint())
        elif action_value == bot_wire_response_action_kinds["selectInfoToReveal"]:
            frame = DecisionResponse(
                "decisionResponse", request_id, "selectInfoToReveal", reader.varint()
            )
        else:
            raise ValueError("unknown response action kind")
    else:
        raise ValueError("unknown bot wire message kind")
    reader.finish()
    return frame
