"""Byte-exact port of the shared seeded shuffle.

The TS side (``packages/shared/src/shuffle.ts``) seeds random-js's
MersenneTwister19937 with the UTF-8 bytes of the seed string via
``seedWithArray`` and Fisher-Yates-shuffles with ``rng.integer(0, i)``.
Trace replay and same-seed reproducibility both depend on this port
producing identical permutations; ``tests/sim/test_rng.py`` pins it to
fixtures generated by the real TS implementation.
"""

from __future__ import annotations

from collections.abc import Sequence
from typing import Any, TypeVar

import numpy as np
from numpy.typing import NDArray

_T = TypeVar("_T")

_UINT32_MASK = 0xFFFFFFFF
_UINT32_SIZE = 0x100000000
_N = 624


class _MersenneTwister:
    """MT19937 matching random-js: init_by_array seeding, signed-int32 output."""

    def __init__(self, key: Sequence[int]) -> None:
        mt = [0] * _N
        mt[0] = 19650218
        for i in range(1, _N):
            mt[i] = (1812433253 * (mt[i - 1] ^ (mt[i - 1] >> 30)) + i) & _UINT32_MASK
        i, j = 1, 0
        for _ in range(max(_N, len(key))):
            mixed = (mt[i] ^ ((mt[i - 1] ^ (mt[i - 1] >> 30)) * 1664525)) + key[j] + j
            mt[i] = mixed & _UINT32_MASK
            i += 1
            j += 1
            if i >= _N:
                mt[0] = mt[_N - 1]
                i = 1
            if j >= len(key):
                j = 0
        for _ in range(_N - 1):
            mt[i] = ((mt[i] ^ ((mt[i - 1] ^ (mt[i - 1] >> 30)) * 1566083941)) - i) & _UINT32_MASK
            i += 1
            if i >= _N:
                mt[0] = mt[_N - 1]
                i = 1
        mt[0] = 0x80000000
        self._mt = mt
        self._index = _N

    def _generate(self) -> None:
        mt = self._mt
        for i in range(_N):
            y = (mt[i] & 0x80000000) | (mt[(i + 1) % _N] & 0x7FFFFFFF)
            mt[i] = mt[(i + 397) % _N] ^ (y >> 1)
            if y & 1:
                mt[i] ^= 0x9908B0DF
        self._index = 0

    def next_uint32(self) -> int:
        if self._index >= _N:
            self._generate()
        y = self._mt[self._index]
        self._index += 1
        y ^= y >> 11
        y ^= (y << 7) & 0x9D2C5680
        y ^= (y << 15) & 0xEFC60000
        y ^= y >> 18
        return y & _UINT32_MASK


def _integer_upto(rng: _MersenneTwister, max_inclusive: int) -> int:
    """random-js ``integer(0, max)`` for 0 <= max < 2**32 - 1."""
    if max_inclusive == 0:
        return 0
    if (max_inclusive & (max_inclusive + 1)) == 0:
        # Power-of-two-minus-one range: mask the signed int32 output. Low bits are
        # unaffected by the sign interpretation, so masking the uint32 is identical.
        return rng.next_uint32() & max_inclusive
    extended_range = max_inclusive + 1
    maximum = extended_range * (_UINT32_SIZE // extended_range)
    while True:
        # random-js's engine.next() returns a *signed* int32 (the tempered MT
        # output reinterpreted via `| 0`), and its uint32() distribution does
        # `engine.next() >>> 0` - a bit-pattern reinterpretation as unsigned,
        # not an arithmetic offset. Since next_uint32() already tracks that
        # same bit pattern as an unsigned value throughout, it *is* the
        # uint32() result directly; no further transform is needed here.
        value = rng.next_uint32()
        if value < maximum:
            return value % extended_range


def shuffled(items: Sequence[_T], seed: str) -> list[_T]:
    """Return a shuffled copy of ``items``; same algorithm and output as the
    TS ``shuffled(arr, seed)`` in ``@pocketrocks/shared``."""
    if not seed:
        # An empty seed would hand init_by_array an empty key (undefined
        # behavior upstream too) — reject it before it becomes an IndexError.
        raise ValueError("seed must be a non-empty string")
    result = list(items)
    rng = _MersenneTwister(list(seed.encode("utf-8")))
    for i in range(len(result) - 1, 0, -1):
        j = _integer_upto(rng, i)
        if j != i:
            result[i], result[j] = result[j], result[i]
    return result


class _BatchMersenneTwister:
    """MT19937 state advanced independently across a vector of seeds."""

    def __init__(self, seeds: Sequence[str]) -> None:
        encoded = [seed.encode("utf-8") for seed in seeds]
        key_lengths = np.fromiter((len(key) for key in encoded), dtype=np.intp)
        keys = np.zeros((len(encoded), int(key_lengths.max())), dtype=np.uint32)
        for row, key in enumerate(encoded):
            keys[row, : len(key)] = np.frombuffer(key, dtype=np.uint8)

        mt = np.zeros((len(encoded), _N), dtype=np.uint32)
        mt[:, 0] = 19650218
        for index in range(1, _N):
            previous = mt[:, index - 1].astype(np.uint64)
            mixed = previous ^ (previous >> np.uint64(30))
            mt[:, index] = (
                1812433253 * mixed + index
            ).astype(np.uint32)

        key_indices = np.zeros(len(encoded), dtype=np.intp)
        iteration_counts = np.maximum(_N, key_lengths)
        state_indices = np.ones(len(encoded), dtype=np.intp)
        for iteration in range(int(iteration_counts.max())):
            rows = np.flatnonzero(iteration < iteration_counts)
            indices = state_indices[rows]
            previous = mt[rows, indices - 1].astype(np.uint64)
            current = mt[rows, indices].astype(np.uint64)
            mixed = current ^ ((previous ^ (previous >> np.uint64(30))) * 1664525)
            mixed += keys[rows, key_indices[rows]].astype(np.uint64)
            mixed += key_indices[rows].astype(np.uint64)
            mt[rows, indices] = mixed.astype(np.uint32)
            next_indices = indices + 1
            wrapped = next_indices >= _N
            wrapped_rows = rows[wrapped]
            mt[wrapped_rows, 0] = mt[wrapped_rows, _N - 1]
            next_indices[wrapped] = 1
            state_indices[rows] = next_indices
            key_indices[rows] += 1
            wrapped_keys = key_indices[rows] >= key_lengths[rows]
            key_indices[rows[wrapped_keys]] = 0

        rows = np.arange(len(encoded))
        for _ in range(_N - 1):
            previous = mt[rows, state_indices - 1].astype(np.uint64)
            current = mt[rows, state_indices].astype(np.uint64)
            mixed = current ^ ((previous ^ (previous >> np.uint64(30))) * 1566083941)
            mt[rows, state_indices] = (
                mixed + _UINT32_SIZE - state_indices.astype(np.uint64)
            ).astype(np.uint32)
            next_indices = state_indices + 1
            wrapped = next_indices >= _N
            wrapped_rows = rows[wrapped]
            mt[wrapped_rows, 0] = mt[wrapped_rows, _N - 1]
            next_indices[wrapped] = 1
            state_indices = next_indices
        mt[:, 0] = 0x80000000

        self._mt = mt
        self._index = np.full(len(encoded), _N, dtype=np.intp)

    def copy(self) -> _BatchMersenneTwister:
        result = object.__new__(_BatchMersenneTwister)
        result._mt = self._mt.copy()
        result._index = self._index.copy()
        return result

    def _generate(self, rows: NDArray[np.intp]) -> None:
        mt = self._mt[rows].copy()
        for index in range(_N):
            y = (mt[:, index] & np.uint32(0x80000000)) | (
                mt[:, (index + 1) % _N] & np.uint32(0x7FFFFFFF)
            )
            next_value = mt[:, (index + 397) % _N] ^ (y >> np.uint32(1))
            mt[:, index] = np.where(
                y & np.uint32(1),
                next_value ^ np.uint32(0x9908B0DF),
                next_value,
            )
        self._mt[rows] = mt
        self._index[rows] = 0

    def next_uint32(self, rows: NDArray[np.intp]) -> NDArray[np.uint32]:
        expired = rows[self._index[rows] >= _N]
        if expired.size:
            self._generate(expired)
        values = self._mt[rows, self._index[rows]].copy()
        self._index[rows] += 1
        values ^= values >> np.uint32(11)
        values ^= (values << np.uint32(7)) & np.uint32(0x9D2C5680)
        values ^= (values << np.uint32(15)) & np.uint32(0xEFC60000)
        values ^= values >> np.uint32(18)
        return values


def _batch_integer_upto(
    rng: _BatchMersenneTwister,
    max_inclusive: int,
    rows: NDArray[np.intp],
) -> NDArray[np.intp]:
    if max_inclusive == 0:
        return np.zeros(rows.size, dtype=np.intp)
    if (max_inclusive & (max_inclusive + 1)) == 0:
        return (rng.next_uint32(rows) & np.uint32(max_inclusive)).astype(np.intp)

    extended_range = max_inclusive + 1
    maximum = extended_range * (_UINT32_SIZE // extended_range)
    result = np.empty(rows.size, dtype=np.intp)
    pending_positions: NDArray[np.intp] = np.arange(rows.size)
    while pending_positions.size:
        values = rng.next_uint32(rows[pending_positions]).astype(np.uint64)
        accepted = values < maximum
        result[pending_positions[accepted]] = (
            values[accepted] % extended_range
        ).astype(np.intp)
        pending_positions = pending_positions[~accepted]
    return result


def batch_shuffled_many(
    groups: Sequence[Sequence[_T]],
    seeds: Sequence[str],
) -> tuple[NDArray[Any], ...]:
    """Shuffle each group independently for every seed.

    Each returned array has shape ``(len(seeds), len(group))`` and row ``i``
    exactly matches ``shuffled(group, seeds[i])``. As in scalar setup, every
    group starts from a freshly seeded random-js-compatible MT19937 stream.
    """
    seed_values = tuple(seeds)
    if not seed_values or any(not seed for seed in seed_values):
        raise ValueError("seeds must contain only non-empty strings")

    base_rng = _BatchMersenneTwister(seed_values)
    rows = np.arange(len(seed_values))
    shuffled_groups: list[NDArray[Any]] = []
    for group in groups:
        values = np.asarray(group)
        result = np.broadcast_to(values, (len(seed_values), len(values))).copy()
        rng = base_rng.copy()
        for index in range(len(values) - 1, 0, -1):
            swap_indices = _batch_integer_upto(rng, index, rows)
            current = result[:, index].copy()
            swaps = result[rows, swap_indices].copy()
            result[:, index] = swaps
            result[rows, swap_indices] = current
        shuffled_groups.append(result)
    return tuple(shuffled_groups)
