"""Byte-exact port of the shared seeded shuffle.

The TS side (``packages/shared/src/shuffle.ts``) seeds random-js's
MersenneTwister19937 with the UTF-8 bytes of the seed string via
``seedWithArray`` and Fisher-Yates-shuffles with ``rng.integer(0, i)``.
Trace replay and same-seed reproducibility both depend on this port
producing identical permutations; ``tests/sim/test_rng.py`` pins it to
fixtures generated by the real TS implementation.
"""

from __future__ import annotations

from collections.abc import Sequence
from typing import TypeVar

_T = TypeVar("_T")

_UINT32_MASK = 0xFFFFFFFF
_UINT32_SIZE = 0x100000000
_N = 624


class _MersenneTwister:
    """MT19937 matching random-js: init_by_array seeding, signed-int32 output."""

    def __init__(self, key: Sequence[int]) -> None:
        mt = [0] * _N
        mt[0] = 19650218
        for i in range(1, _N):
            mt[i] = (1812433253 * (mt[i - 1] ^ (mt[i - 1] >> 30)) + i) & _UINT32_MASK
        i, j = 1, 0
        for _ in range(max(_N, len(key))):
            mixed = (mt[i] ^ ((mt[i - 1] ^ (mt[i - 1] >> 30)) * 1664525)) + key[j] + j
            mt[i] = mixed & _UINT32_MASK
            i += 1
            j += 1
            if i >= _N:
                mt[0] = mt[_N - 1]
                i = 1
            if j >= len(key):
                j = 0
        for _ in range(_N - 1):
            mt[i] = ((mt[i] ^ ((mt[i - 1] ^ (mt[i - 1] >> 30)) * 1566083941)) - i) & _UINT32_MASK
            i += 1
            if i >= _N:
                mt[0] = mt[_N - 1]
                i = 1
        mt[0] = 0x80000000
        self._mt = mt
        self._index = _N

    def _generate(self) -> None:
        mt = self._mt
        for i in range(_N):
            y = (mt[i] & 0x80000000) | (mt[(i + 1) % _N] & 0x7FFFFFFF)
            mt[i] = mt[(i + 397) % _N] ^ (y >> 1)
            if y & 1:
                mt[i] ^= 0x9908B0DF
        self._index = 0

    def next_uint32(self) -> int:
        if self._index >= _N:
            self._generate()
        y = self._mt[self._index]
        self._index += 1
        y ^= y >> 11
        y ^= (y << 7) & 0x9D2C5680
        y ^= (y << 15) & 0xEFC60000
        y ^= y >> 18
        return y & _UINT32_MASK


def _integer_upto(rng: _MersenneTwister, max_inclusive: int) -> int:
    """random-js ``integer(0, max)`` for 0 <= max < 2**32 - 1."""
    if max_inclusive == 0:
        return 0
    if (max_inclusive & (max_inclusive + 1)) == 0:
        # Power-of-two-minus-one range: mask the signed int32 output. Low bits are
        # unaffected by the sign interpretation, so masking the uint32 is identical.
        return rng.next_uint32() & max_inclusive
    extended_range = max_inclusive + 1
    maximum = extended_range * (_UINT32_SIZE // extended_range)
    while True:
        # random-js's engine.next() returns a *signed* int32 (the tempered MT
        # output reinterpreted via `| 0`), and its uint32() distribution does
        # `engine.next() >>> 0` - a bit-pattern reinterpretation as unsigned,
        # not an arithmetic offset. Since next_uint32() already tracks that
        # same bit pattern as an unsigned value throughout, it *is* the
        # uint32() result directly; no further transform is needed here.
        value = rng.next_uint32()
        if value < maximum:
            return value % extended_range


def shuffled(items: Sequence[_T], seed: str) -> list[_T]:
    """Return a shuffled copy of ``items``; same algorithm and output as the
    TS ``shuffled(arr, seed)`` in ``@pocketrocks/shared``."""
    result = list(items)
    rng = _MersenneTwister(list(seed.encode("utf-8")))
    for i in range(len(result) - 1, 0, -1):
        j = _integer_upto(rng, i)
        if j != i:
            result[i], result[j] = result[j], result[i]
    return result
